# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Research"
    url: /research
  - title: "Publications"
    url: /publications
  - title: "People"
    url: /people
  - title: "Contact"
    url: /contact


# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:                 'Soft Matter & Active Materials Lab'
description:           'Exploring magnetoelasticity, soft composites, and active matter'
author:                'Nitesh Arora'


# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
